# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chawin Sitawarin
tagline:          'INSERT TAGLINE HERE'
description:      'INSERT DESCRIPTION HERE'
url:              http://chawins.github.io
baseurl:          /

author:
  name:           'Chawin Sitawarin'
  url:            https://twitter.com/CSitawarin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chawins/chawins.github.io

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
