# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Chawin Sitawarin
tagline:          'INSERT TAGLINE HERE'
description:      PhD Student in Computer Science at UC Berkeley
url:              https://chawins.github.io
baseurl:          /

author:
  name:           'Chawin Sitawarin'
  url:            https://twitter.com/CSitawarin

paginate:         5

# Custom vars
version:          1

github:
  repo:           https://github.com/chawins/chawins.github.io
